#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing wkhtmltox ..."
COMMAND=$(cat <<EOF
apt-get install software-properties-common
apt-add-repository --remove "deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main"
apt-add-repository "deb http://apt-archive.postgresql.org/pub/repos/apt bionic-pgdg main"
apt-get -y  update 
apt-get install -y wget xfonts-base xfonts-75dpi libssl1.0-dev openssl
cd /tmp && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-3/wkhtmltox-0.12.6-3.archlinux-x86_64.pkg.tar.xz
cd /tmp && tar xf wkhtmltox-0.12.6-3.archlinux-x86_64.pkg.tar.xz
mv /tmp/wkhtmltox /opt/
cd /usr/local/bin && ln -s /opt/wkhtmltox/bin/wkhtmltopdf && ln -s /opt/wkhtmltox/bin/wkhtmltoimage
echo "-----> wkhtmltox installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
